In [1]:
import time 
import pandas as pd
import numpy as np
import itertools
import sys
import os
import configparser
import datetime
import scipy
from strategy_pool import StrategyPool
from indicator_generator import IndicatorGenerator

In [2]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [3]:
param_dir = ".." + os.sep + "eval_opt_res" + os.sep + "crosssec"

In [4]:
param_df = pd.DataFrame()

i = 0 
for stra in os.listdir(param_dir):
    stra_path = os.path.join(param_dir, stra)
    for res_dir in os.listdir(stra_path):
        res_path = os.path.join(stra_path, res_dir)
        file_path = os.path.join(res_path, "param.txt")
        res_path = os.path.join(res_path, "res.csv" )
        
        print("current param res dir: ", res_dir)
       
        # parse the parameters
        config = configparser.ConfigParser()
        config.read(file_path)
        params = config["params"]
        dic = {}
        for item, value in params.items():
            if item == "start_date" or item == "end_date":
                value = value.split(" ")[0]
                dic[item] = datetime.datetime.strptime(value, "%Y-%m-%d")
            elif item in ["indicator_cal_method", "freq_unit", "res_dir", "index_col", "fut_pool_gen_method"]:
                dic[item] = value
                pass
            else:
                dic[item] = eval(params[item])
        
        # parse the result 
        res = pd.read_csv(res_path)
        res = res.set_index(["indi"])
        for val in ["max_drawdown", "sharpe", "returns", "ir", "std"]:
            dic[val] = res.loc[val, "value"]
#         print(res.loc["max_drawdown", "value"], res.loc["sharpe", "value"])
        param_df = param_df.append(pd.DataFrame([dic]), ignore_index=True)
        print(dic)
#         print(i)
#         print(" ")
#         print(" ")
        
#         strategy_param["crosssec_" + str(i)] = dic.copy()
        i += 1
        print(i)

current param res dir:  res0
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 10, 'freq_unit': 'D', 'indicator_cal_method': 'hedging_pressure', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 15, 'if_check_vol': True, 'max_drawdown': 0.2949701388187937, 'sharpe': -0.11471543674172885, 'returns': 0.00439401621951612, 'ir': -0.007226393265685149, 'std': 847658.1257069018}
1
current param res dir:  res1
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': True, 'is_main_contract_indi': True, 'n_nearest_index_op': None, 'n_nearest_index_indi': None, 'freq': 50, 'freq_unit': 'D', 'indicator_cal_method': 'hedging_pressure', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 45, 'if_check_vol': False, 'max_drawdown': 0.18127407707458928, 'sharpe': 0.27280130617618004, 'returns': 0.032458069455707415, 'ir': 0.01718486698751812, 'std': 827328.9467291925}
2
current param res dir:  res2
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': True, 'is_main_contract_indi': True, 'n_nearest_index_op': None, 'n_nearest_index_indi': None, 'freq': 10, 'freq_unit': 'D', 'indicator_cal_method': 'hedging_pressure', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 120, 'if_check_vol': False, 'max_drawdown': 0.28906478705422256, 'sharpe': -0.01171839244063827, 'returns': 0.01108995293534384, 'ir': -0.0007381893372235247, 'std': 878276.383013127}
3
current param res dir:  res3
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 10, 'freq_unit': 'D', 'indicator_cal_method': 'hedging_pressure', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.15, 'bottom': 0.15, 'num_days': 15, 'if_check_vol': True, 'max_drawdown': 0.20035030116210653, 'sharpe': 0.14051525879888094, 'returns': 0.037052457630965666, 'ir': 0.008851629290279037, 'std': 702043.7536117418}
4
current param res dir:  res0
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 10, 'freq_unit': 'D', 'indicator_cal_method': 'inflation', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.15, 'bottom': 0.15, 'num_days': 15, 'if_check_vol': False, 'index_col': 'm2m', 'num_durations': 20, 'max_drawdown': 0.2564907782867143, 'sharpe': 0.5600033990447777, 'returns': 0.09847131000364044, 'ir': 0.035276898267222564, 'std': 989240.5876435542}
5
current param res dir:  res1
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 10, 'freq_unit': 'D', 'indicator_cal_method': 'inflation', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.2, 'bottom': 0.2, 'num_days': 15, 'if_check_vol': False, 'index_col': 'm2m', 'num_durations': 20, 'max_drawdown': 0.21698271864177066, 'sharpe': 0.8525336204009888, 'returns': 0.13575677720529344, 'ir': 0.053704570092918034, 'std': 842628.5719523134}
6
current param res dir:  res10
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 20, 'freq_unit': 'D', 'indicator_cal_method': 'inflation', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 15, 'if_check_vol': False, 'index_col': 'y2y_1', 'num_durations': 60, 'max_drawdown': 0.2583881122042557, 'sharpe': 0.8365354760684198, 'returns': 0.14450231279583078, 'ir': 0.05269678172762055, 'std': 1239021.62112678}
7
current param res dir:  res11
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'inflation', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.15, 'bottom': 0.15, 'num_days': 15, 'if_check_vol': False, 'index_col': 'y2y_1', 'num_durations': 40, 'max_drawdown': 0.3128361503352829, 'sharpe': 0.4591263765476831, 'returns': 0.07094573838200735, 'ir': 0.028922243159413507, 'std': 993701.7341677144}
8
current param res dir:  res2
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 20, 'freq_unit': 'D', 'indicator_cal_method': 'inflation', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.15, 'bottom': 0.15, 'num_days': 15, 'if_check_vol': True, 'index_col': 'y2y_1', 'num_durations': 60, 'max_drawdown': 0.1768234723424056, 'sharpe': 0.9444655217418091, 'returns': 0.13542860618943536, 'ir': 0.05949573553342127, 'std': 1052019.1395891076}
9
current param res dir:  res3
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 20, 'freq_unit': 'D', 'indicator_cal_method': 'inflation', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.15, 'bottom': 0.15, 'num_days': 15, 'if_check_vol': False, 'index_col': 'y2y_1', 'num_durations': 60, 'max_drawdown': 0.17438361155052606, 'sharpe': 1.1058019680927842, 'returns': 0.13182805321430485, 'ir': 0.06965897635379258, 'std': 992940.5090949936}
10
current param res dir:  res4
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 20, 'freq_unit': 'D', 'indicator_cal_method': 'inflation', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 15, 'if_check_vol': True, 'index_col': 'y2y_1', 'num_durations': 40, 'max_drawdown': 0.26390516520875257, 'sharpe': 0.07600805218396617, 'returns': 0.09742787787403503, 'ir': 0.004788057231361765, 'std': 1331611.4117973642}
11
current param res dir:  res5
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 20, 'freq_unit': 'D', 'indicator_cal_method': 'inflation', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 15, 'if_check_vol': False, 'index_col': 'y2y_1', 'num_durations': 40, 'max_drawdown': 0.2967948785774091, 'sharpe': 0.2313214777703629, 'returns': 0.13992605692621193, 'ir': 0.01457188340686515, 'std': 1305271.586091524}
12
current param res dir:  res6
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': True, 'is_main_contract_indi': True, 'n_nearest_index_op': None, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'inflation', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 15, 'if_check_vol': False, 'index_col': 'y2y_1', 'num_durations': 40, 'max_drawdown': 0.25666746362302084, 'sharpe': 0.5156904041248291, 'returns': 0.10272943645003994, 'ir': 0.03248544197182608, 'std': 1250326.077530877}
13
current param res dir:  res7
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'inflation', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 15, 'if_check_vol': False, 'index_col': 'y2y_1', 'num_durations': 40, 'max_drawdown': 0.3654131142249876, 'sharpe': 0.4747744094937197, 'returns': 0.11650082664465268, 'ir': 0.0299079765804268, 'std': 1233906.3994495512}
14
current param res dir:  res8

{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': True, 'is_main_contract_indi': True, 'n_nearest_index_op': None, 'n_nearest_index_indi': None, 'freq': 20, 'freq_unit': 'D', 'indicator_cal_method': 'inflation', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 15, 'if_check_vol': False, 'index_col': 'y2y_1', 'num_durations': 60, 'max_drawdown': 0.2125137045541257, 'sharpe': 0.95799113644596, 'returns': 0.16616268984026147, 'ir': 0.06034776917238467, 'std': 1314542.5649592823}
15
current param res dir:  res9
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 20, 'freq_unit': 'D', 'indicator_cal_method': 'inflation', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 15, 'if_check_vol': True, 'index_col': 'y2y_1', 'num_durations': 60, 'max_drawdown': 0.2316060283372453, 'sharpe': 0.843023544246628, 'returns': 0.17598063186225746, 'ir': 0.053105491605924614, 'std': 1281795.611055607}
16
current param res dir:  res0
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['sr', 'c', 'cf', 'jd', 'cs', 'lr', 'wh', 'jr', 'pm', 'ap', 'cy', 'wt', 'er', 'cj', 'ri', 'ws', 'gn', 'rr'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 3, 'n_nearest_index_indi': None, 'freq': 10, 'freq_unit': 'D', 'indicator_cal_method': 'momentum', 'if_save_res': True, 'res_dir': 'eval_1211', 'num_durations': 6, 'max_drawdown': 0.3131003511483803, 'sharpe': -0.07429874125932995, 'returns': -0.014540677156528622, 'ir': -0.004680380764221931, 'std': 910926.7358381874}
17
current param res dir:  res1
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['sr', 'c', 'cf', 'jd', 'cs', 'lr', 'wh', 'jr', 'pm', 'ap', 'cy', 'wt', 'er', 'cj', 'ri', 'ws', 'gn', 'rr'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 3, 'n_nearest_index_indi': None, 'freq': 10, 'freq_unit': 'D', 'indicator_cal_method': 'momentum', 'if_save_res': True, 'res_dir': 'eval_1211', 'num_durations': 12, 'max_drawdown': 0.3131003511483803, 'sharpe': -0.07429874125932995, 'returns': -0.014540677156528622, 'ir': -0.004680380764221931, 'std': 910926.7358381874}
18
current param res dir:  res10
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['ss', 'al', 'cu', 'pb', 'wr', 'zn', 'ni', 'hc', 'au', 'ag', 'sn'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': True, 'is_main_contract_indi': True, 'n_nearest_index_op': None, 'n_nearest_index_indi': None, 'freq': 5, 'freq_unit': 'D', 'indicator_cal_method': 'momentum', 'if_save_res': True, 'res_dir': 'eval_1211', 'num_durations': 24, 'max_drawdown': 0.25299953014179943, 'sharpe': 0.007298717380580126, 'returns': 0.009752876990101729, 'ir': 0.0004597759780657035, 'std': 932996.4197208419}
19
current param res dir:  res11
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['sr', 'c', 'cf', 'jd', 'cs', 'lr', 'wh', 'jr', 'pm', 'ap', 'cy', 'wt', 'er', 'cj', 'ri', 'ws', 'gn', 'rr', 'ss', 'al', 'cu', 'pb', 'wr', 'zn', 'ni', 'hc', 'au', 'ag', 'sn', 'a', 'b', 'y', 'm', 'oi', 'p', 'rm', 'rs', 'ro', 'ru', 'sc', 'tc', 'zc', 'l', 'ta', 'pp', 'bu', 'ma', 'fu', 'me', 'eg', 'sp', 'nr', 'eb', 'ur', 't', 'ts', 'ih', 'if', 'tf', 'ic'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 3, 'n_nearest_index_indi': None, 'freq': 10, 'freq_unit': 'D', 'indicator_cal_method': 'momentum', 'if_save_res': True, 'res_dir': 'eval_1211', 'num_durations': 6, 'max_drawdown': 0.17085305821775573, 'sharpe': 0.0904409149481809, 'returns': 0.011253944120149944, 'ir': 0.005697242126143589, 'std': 750873.3184949959}
20
current param res dir:  res2
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['sr', 'c', 'cf', 'jd', 'cs', 'lr', 'wh', 'jr', 'pm', 'ap', 'cy', 'wt', 'er', 'cj', 'ri', 'ws', 'gn', 'rr', 'ss', 'al', 'cu', 'pb', 'wr', 'zn', 'ni', 'hc', 'au', 'ag', 'sn', 'a', 'b', 'y', 'm', 'oi', 'p', 'rm', 'rs', 'ro', 'ru', 'sc', 'tc', 'zc', 'l', 'ta', 'pp', 'bu', 'ma', 'fu', 'me', 'eg', 'sp', 'nr', 'eb', 'ur', 't', 'ts', 'ih', 'if', 'tf', 'ic'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 3, 'n_nearest_index_indi': None, 'freq': 10, 'freq_unit': 'D', 'indicator_cal_method': 'momentum', 'if_save_res': True, 'res_dir': 'eval_1211', 'num_durations': 12, 'max_drawdown': 0.17085305821775573, 'sharpe': 0.0904409149481809, 'returns': 0.011253944120149944, 'ir': 0.005697242126143589, 'std': 750873.3184949959}
21
current param res dir:  res3
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['sr', 'c', 'cf', 'jd', 'cs', 'lr', 'wh', 'jr', 'pm', 'ap', 'cy', 'wt', 'er', 'cj', 'ri', 'ws', 'gn', 'rr', 'ss', 'al', 'cu', 'pb', 'wr', 'zn', 'ni', 'hc', 'au', 'ag', 'sn', 'a', 'b', 'y', 'm', 'oi', 'p', 'rm', 'rs', 'ro', 'ru', 'sc', 'tc', 'zc', 'l', 'ta', 'pp', 'bu', 'ma', 'fu', 'me', 'eg', 'sp', 'nr', 'eb', 'ur', 't', 'ts', 'ih', 'if', 'tf', 'ic'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 3, 'n_nearest_index_indi': None, 'freq': 10, 'freq_unit': 'D', 'indicator_cal_method': 'momentum', 'if_save_res': True, 'res_dir': 'eval_1211', 'num_durations': 24, 'max_drawdown': 0.17085305821775573, 'sharpe': 0.0904409149481809, 'returns': 0.011253944120149944, 'ir': 0.005697242126143589, 'std': 750873.3184949959}
22
current param res dir:  res4
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['sr', 'c', 'cf', 'jd', 'cs', 'lr', 'wh', 'jr', 'pm', 'ap', 'cy', 'wt', 'er', 'cj', 'ri', 'ws', 'gn', 'rr'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 3, 'n_nearest_index_indi': None, 'freq': 10, 'freq_unit': 'D', 'indicator_cal_method': 'momentum', 'if_save_res': True, 'res_dir': 'eval_1211', 'num_durations': 24, 'max_drawdown': 0.3131003511483803, 'sharpe': -0.07429874125932995, 'returns': -0.014540677156528622, 'ir': -0.004680380764221931, 'std': 910926.7358381874}
23
current param res dir:  res5
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['t', 'ts', 'ih', 'if', 'tf', 'ic'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': True, 'is_main_contract_indi': True, 'n_nearest_index_op': None, 'n_nearest_index_indi': None, 'freq': 5, 'freq_unit': 'D', 'indicator_cal_method': 'momentum', 'if_save_res': True, 'res_dir': 'eval_1211', 'num_durations': 6, 'max_drawdown': 0.2715574783635816, 'sharpe': 0.3512350750859859, 'returns': 0.09771152147773804, 'ir': 0.0221257300095385, 'std': 1741488.6247406213}
24
current param res dir:  res6
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['t', 'ts', 'ih', 'if', 'tf', 'ic'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': True, 'is_main_contract_indi': True, 'n_nearest_index_op': None, 'n_nearest_index_indi': None, 'freq': 5, 'freq_unit': 'D', 'indicator_cal_method': 'momentum', 'if_save_res': True, 'res_dir': 'eval_1211', 'num_durations': 12, 'max_drawdown': 0.2715574783635816, 'sharpe': 0.3512350750859859, 'returns': 0.09771152147773804, 'ir': 0.0221257300095385, 'std': 1741488.6247406213}
25
current param res dir:  res7
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['t', 'ts', 'ih', 'if', 'tf', 'ic'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': True, 'is_main_contract_indi': True, 'n_nearest_index_op': None, 'n_nearest_index_indi': None, 'freq': 5, 'freq_unit': 'D', 'indicator_cal_method': 'momentum', 'if_save_res': True, 'res_dir': 'eval_1211', 'num_durations': 24, 'max_drawdown': 0.2715574783635816, 'sharpe': 0.3512350750859859, 'returns': 0.09771152147773804, 'ir': 0.0221257300095385, 'std': 1741488.6247406213}
26
current param res dir:  res8
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['ss', 'al', 'cu', 'pb', 'wr', 'zn', 'ni', 'hc', 'au', 'ag', 'sn'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': True, 'is_main_contract_indi': True, 'n_nearest_index_op': None, 'n_nearest_index_indi': None, 'freq': 5, 'freq_unit': 'D', 'indicator_cal_method': 'momentum', 'if_save_res': True, 'res_dir': 'eval_1211', 'num_durations': 6, 'max_drawdown': 0.25299953014179943, 'sharpe': 0.007298717380580126, 'returns': 0.009752876990101729, 'ir': 0.0004597759780657035, 'std': 932996.4197208419}
27
current param res dir:  res9
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['ss', 'al', 'cu', 'pb', 'wr', 'zn', 'ni', 'hc', 'au', 'ag', 'sn'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': True, 'is_main_contract_indi': True, 'n_nearest_index_op': None, 'n_nearest_index_indi': None, 'freq': 5, 'freq_unit': 'D', 'indicator_cal_method': 'momentum', 'if_save_res': True, 'res_dir': 'eval_1211', 'num_durations': 12, 'max_drawdown': 0.25299953014179943, 'sharpe': 0.007298717380580126, 'returns': 0.009752876990101729, 'ir': 0.0004597759780657035, 'std': 932996.4197208419}
28
current param res dir:  res0

{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'open_interest', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 30, 'if_check_vol': False, 'max_drawdown': 0.11753627157452876, 'sharpe': 0.8852270569764618, 'returns': 0.15803390344623455, 'ir': 0.05576406301393625, 'std': 943177.03910354}
29
current param res dir:  res1
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'open_interest', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 60, 'if_check_vol': False, 'max_drawdown': 0.17643399170545815, 'sharpe': 0.6248922284881314, 'returns': 0.12174453339156205, 'ir': 0.0393645103046797, 'std': 910759.7599267834}
30
current param res dir:  res2
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'open_interest', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 15, 'if_check_vol': False, 'max_drawdown': 0.1573142510058023, 'sharpe': 0.8645832319922238, 'returns': 0.1668362377562528, 'ir': 0.054463624275425886, 'std': 985178.0767978531}
31
current param res dir:  res3
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'open_interest', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.15, 'bottom': 0.15, 'num_days': 30, 'if_check_vol': False, 'max_drawdown': 0.09738175671184134, 'sharpe': 0.8558941638142231, 'returns': 0.12868022247086572, 'ir': 0.053916264429619325, 'std': 787698.9886443508}
32
current param res dir:  res4
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': True, 'is_main_contract_indi': True, 'n_nearest_index_op': None, 'n_nearest_index_indi': None, 'freq': 50, 'freq_unit': 'D', 'indicator_cal_method': 'open_interest', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 15, 'if_check_vol': False, 'max_drawdown': 0.1268386231948207, 'sharpe': 0.6022273542303916, 'returns': 0.1236572916823125, 'ir': 0.03793675742890519, 'std': 906064.6659714921}
33
current param res dir:  res5
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': True, 'is_main_contract_indi': True, 'n_nearest_index_op': None, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'open_interest', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.15, 'bottom': 0.15, 'num_days': 45, 'if_check_vol': False, 'max_drawdown': 0.09528696608788012, 'sharpe': 0.8241523028259405, 'returns': 0.13284031314248596, 'ir': 0.05191671513615795, 'std': 719164.6386994305}
34
current param res dir:  res6
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'open_interest', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.15, 'bottom': 0.15, 'num_days': 45, 'if_check_vol': False, 'max_drawdown': 0.0999016953230562, 'sharpe': 0.7675439012959443, 'returns': 0.11756447660304616, 'ir': 0.04835072102746132, 'std': 761435.2769948291}
35
current param res dir:  res7
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 50, 'freq_unit': 'D', 'indicator_cal_method': 'open_interest', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 15, 'if_check_vol': True, 'max_drawdown': 0.1404981269271946, 'sharpe': 0.6136216360928947, 'returns': 0.1190909700363172, 'ir': 0.038654529718818456, 'std': 904100.7270876705}
36
current param res dir:  res8
{'fut_pool_gen_method': 'static', 'fut_pool_gen_param': None, 'future_pool': ['a', 'b', 'c', 'l', 'v', 'j', 'jm', 'm', 'p', 'y', 'fu', 'ru', 'al', 'au', 'cu', 'pb', 'rb', 'wr', 'zn', 'ag', 'ma', 'sr', 'wh', 'pm', 'cf', 'ta', 'fg', 'oi', 'rm', 'rs'], 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 1, 'n_nearest_index_indi': None, 'freq': 50, 'freq_unit': 'D', 'indicator_cal_method': 'open_interest', 'if_save_res': True, 'res_dir': 'eval_1211', 'weighted': False, 'top': 0.1, 'bottom': 0.1, 'num_days': 15, 'if_check_vol': False, 'max_drawdown': 0.14134372241689167, 'sharpe': 0.7765343339159292, 'returns': 0.14772442639847153, 'ir': 0.04891706504868423, 'std': 963159.5048948769}
37
current param res dir:  res0
{'fut_pool_gen_method': 'dynamic', 'fut_pool_gen_param': {'type_list': ['能化', '金属'], 'cal_method': 'single', 'method_param': {'time_range': 120, 'method': 'liquidity', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'freq': 30, 'freq_unit': 'D', 'future_pool': ['ru', 'sc', 'tc', 'zc', 'l', 'ta', 'pp', 'bu', 'ma', 'fu', 'me', 'eg', 'sp', 'nr', 'eb', 'ur', 'ss', 'al', 'cu', 'pb', 'wr', 'zn', 'ni', 'hc', 'au', 'ag', 'sn'], 'is_main_contract_indi': True}, 'sel_fut_param': {'lower_bound': 1, 'upper_bound': 4, 'if_use_amount': True, 'total_num': 10, 'percent': 0.5}, 'method_2_param': {'time_range': 30, 'method': 'liquidity'}, 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'freq_unit': 'D', 'freq': 30}, 'future_pool': None, 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 3, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'term_structure', 'if_save_res': True, 'res_dir': 'eval_1211', 'max_drawdown': 0.20007180574025574, 'sharpe': 1.333470155237109, 'returns': 0.25462010706584937, 'ir': 0.0840007240829544, 'std': 1060385.3624932747}
38
current param res dir:  res1
{'fut_pool_gen_method': 'dynamic', 'fut_pool_gen_param': {'type_list': ['能化', '金属'], 'cal_method': 'single', 'method_param': {'time_range': 120, 'method': 'liquidity', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'freq': 30, 'freq_unit': 'D', 'future_pool': ['ru', 'sc', 'tc', 'zc', 'l', 'ta', 'pp', 'bu', 'ma', 'fu', 'me', 'eg', 'sp', 'nr', 'eb', 'ur', 'ss', 'al', 'cu', 'pb', 'wr', 'zn', 'ni', 'hc', 'au', 'ag', 'sn'], 'is_main_contract_indi': True}, 'sel_fut_param': {'lower_bound': 2, 'upper_bound': 6, 'if_use_amount': True, 'total_num': 15, 'percent': 0.5}, 'method_2_param': {'time_range': 30, 'method': 'liquidity'}, 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'freq_unit': 'D', 'freq': 30}, 'future_pool': None, 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 3, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'term_structure', 'if_save_res': True, 'res_dir': 'eval_1211', 'max_drawdown': 0.17915398612149774, 'sharpe': 1.5477265211122502, 'returns': 0.2605006420899628, 'ir': 0.09749760648576604, 'std': 904468.267539444}
39
current param res dir:  res2
{'fut_pool_gen_method': 'dynamic', 'fut_pool_gen_param': {'type_list': ['能化', '金属'], 'cal_method': 'single', 'method_param': {'time_range': 120, 'method': 'liquidity', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'freq': 30, 'freq_unit': 'D', 'future_pool': ['ru', 'sc', 'tc', 'zc', 'l', 'ta', 'pp', 'bu', 'ma', 'fu', 'me', 'eg', 'sp', 'nr', 'eb', 'ur', 'ss', 'al', 'cu', 'pb', 'wr', 'zn', 'ni', 'hc', 'au', 'ag', 'sn'], 'is_main_contract_indi': True}, 'sel_fut_param': {'lower_bound': 2, 'upper_bound': 8, 'if_use_amount': True, 'total_num': 10, 'percent': 0.5}, 'method_2_param': {'time_range': 30, 'method': 'liquidity'}, 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'freq_unit': 'D', 'freq': 30}, 'future_pool': None, 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 3, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'term_structure', 'if_save_res': True, 'res_dir': 'eval_1211', 'max_drawdown': 0.15347502777604788, 'sharpe': 1.6020303857084364, 'returns': 0.2616478757829336, 'ir': 0.10091842841317636, 'std': 884419.5471394366}
40
current param res dir:  res3
{'fut_pool_gen_method': 'dynamic', 'fut_pool_gen_param': {'type_list': ['能化', '金属'], 'cal_method': 'single', 'method_param': {'time_range': 120, 'method': 'liquidity', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'freq': 30, 'freq_unit': 'D', 'future_pool': ['ru', 'sc', 'tc', 'zc', 'l', 'ta', 'pp', 'bu', 'ma', 'fu', 'me', 'eg', 'sp', 'nr', 'eb', 'ur', 'ss', 'al', 'cu', 'pb', 'wr', 'zn', 'ni', 'hc', 'au', 'ag', 'sn'], 'is_main_contract_indi': True}, 'sel_fut_param': {'lower_bound': 2, 'upper_bound': 8, 'if_use_amount': True, 'total_num': 15, 'percent': 0.5}, 'method_2_param': {'time_range': 30, 'method': 'liquidity'}, 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'freq_unit': 'D', 'freq': 30}, 'future_pool': None, 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 3, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'term_structure', 'if_save_res': True, 'res_dir': 'eval_1211', 'max_drawdown': 0.17701110212975296, 'sharpe': 1.4895445876003417, 'returns': 0.23817011912876476, 'ir': 0.09383248917935164, 'std': 851004.8939892697}
41
current param res dir:  res4
{'fut_pool_gen_method': 'dynamic', 'fut_pool_gen_param': {'type_list': ['能化', '金属'], 'cal_method': 'single', 'method_param': {'time_range': 120, 'method': 'liquidity', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'freq': 30, 'freq_unit': 'D', 'future_pool': ['ru', 'sc', 'tc', 'zc', 'l', 'ta', 'pp', 'bu', 'ma', 'fu', 'me', 'eg', 'sp', 'nr', 'eb', 'ur', 'ss', 'al', 'cu', 'pb', 'wr', 'zn', 'ni', 'hc', 'au', 'ag', 'sn'], 'is_main_contract_indi': True}, 'sel_fut_param': {'lower_bound': 2, 'upper_bound': 8, 'if_use_amount': True, 'total_num': 20, 'percent': 0.5}, 'method_2_param': {'time_range': 30, 'method': 'liquidity'}, 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'freq_unit': 'D', 'freq': 30}, 'future_pool': None, 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 3, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'term_structure', 'if_save_res': True, 'res_dir': 'eval_1211', 'max_drawdown': 0.17701110212975296, 'sharpe': 1.4895445876003417, 'returns': 0.23817011912876476, 'ir': 0.09383248917935164, 'std': 851004.8939892697}
42
current param res dir:  res5
{'fut_pool_gen_method': 'dynamic', 'fut_pool_gen_param': {'type_list': ['能化', '金属'], 'cal_method': 'single', 'method_param': {'time_range': 120, 'method': 'liquidity', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'freq': 30, 'freq_unit': 'D', 'future_pool': ['ru', 'sc', 'tc', 'zc', 'l', 'ta', 'pp', 'bu', 'ma', 'fu', 'me', 'eg', 'sp', 'nr', 'eb', 'ur', 'ss', 'al', 'cu', 'pb', 'wr', 'zn', 'ni', 'hc', 'au', 'ag', 'sn'], 'is_main_contract_indi': True}, 'sel_fut_param': {'lower_bound': 3, 'upper_bound': 8, 'if_use_amount': True, 'total_num': 10, 'percent': 0.5}, 'method_2_param': {'time_range': 30, 'method': 'liquidity'}, 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'freq_unit': 'D', 'freq': 30}, 'future_pool': None, 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2018, 12, 31, 0, 0), 'is_main_contract_op': False, 'is_main_contract_indi': True, 'n_nearest_index_op': 3, 'n_nearest_index_indi': None, 'freq': 30, 'freq_unit': 'D', 'indicator_cal_method': 'term_structure', 'if_save_res': True, 'res_dir': 'eval_1211', 'max_drawdown': 0.15347502777604788, 'sharpe': 1.6020303857084364, 'returns': 0.2616478757829336, 'ir': 0.10091842841317636, 'std': 884419.5471394366}
43

In [5]:
param_df

,bottom,end_date,freq,freq_unit,fut_pool_gen_method,fut_pool_gen_param,future_pool,if_check_vol,if_save_res,index_col,indicator_cal_method,ir,is_main_contract_indi,is_main_contract_op,max_drawdown,n_nearest_index_indi,n_nearest_index_op,num_days,num_durations,res_dir,returns,sharpe,start_date,std,top,weighted
0,0.10,2018-12-31,10,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,NaN,hedging_pressure,-0.007226,True,False,0.294970,None,1,15.0,NaN,eval_1211,0.004394,-0.114715,2010-01-01,8.476581e+05,0.10,False
1,0.10,2018-12-31,50,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,hedging_pressure,0.017185,True,True,0.181274,None,None,45.0,NaN,eval_1211,0.032458,0.272801,2010-01-01,8.273289e+05,0.10,False
2,0.10,2018-12-31,10,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,hedging_pressure,-0.000738,True,True,0.289065,None,None,120.0,NaN,eval_1211,0.011090,-0.011718,2010-01-01,8.782764e+05,0.10,False
3,0.15,2018-12-31,10,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,NaN,hedging_pressure,0.008852,True,False,0.200350,None,1,15.0,NaN,eval_1211,0.037052,0.140515,2010-01-01,7.020438e+05,0.15,False
4,0.15,2018-12-31,10,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,m2m,inflation,0.035277,True,False,0.256491,None,1,15.0,20.0,eval_1211,0.098471,0.560003,2010-01-01,9.892406e+05,0.15,False
5,0.20,2018-12-31,10,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,m2m,inflation,0.053705,True,False,0.216983,None,1,15.0,20.0,eval_1211,0.135757,0.852534,2010-01-01,8.426286e+05,0.20,False
6,0.10,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.052697,True,False,0.258388,None,1,15.0,60.0,eval_1211,0.144502,0.836535,2010-01-01,1.239022e+06,0.10,False
7,0.15,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.028922,True,False,0.312836,None,1,15.0,40.0,eval_1211,0.070946,0.459126,2010-01-01,9.937017e+05,0.15,False
8,0.15,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,y2y_1,inflation,0.059496,True,False,0.176823,None,1,15.0,60.0,eval_1211,0.135429,0.944466,2010-01-01,1.052019e+06,0.15,False
9,0.15,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.069659,True,False,0.174384,None,1,15.0,60.0,eval_1211,0.131828,1.105802,2010-01-01,9.929405e+05,0.15,False
10,0.10,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,y2y_1,inflation,0.004788,True,False,0.263905,None,1,15.0,40.0,eval_1211,0.097428,0.076008,2010-01-01,1.331611e+06,0.10,False
11,0.10,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.014572,True,False,0.296795,None,1,15.0,40.0,eval_1211,0.139926,0.231321,2010-01-01,1.305272e+06,0.10,False
12,0.10,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.032485,True,True,0.256667,None,None,15.0,40.0,eval_1211,0.102729,0.515690,2010-01-01,1.250326e+06,0.10,False
13,0.10,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.029908,True,False,0.365413,None,1,15.0,40.0,eval_1211,0.116501,0.474774,2010-01-01,1.233906e+06,0.10,False
14,0.10,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.060348,True,True,0.212514,None,None,15.0,60.0,eval_1211,0.166163,0.957991,2010-01-01,1.314543e+06,0.10,False
15,0.10,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,y2y_1,inflation,0.053105,True,False,0.231606,None,1,15.0,60.0,eval_1211,0.175981,0.843024,2010-01-01,1.281796e+06,0.10,False
16,NaN,2018-12-31,10,D,static,None,"[sr, c, cf, jd, cs, lr, wh, jr, pm, ap, cy, wt...",NaN,True,NaN,momentum,-0.004680,True,False,0.313100,None,3,NaN,6.0,eval_1211,-0.014541,-0.074299,2010-01-01,9.109267e+05,NaN,NaN
17,NaN,2018-12-31,10,D,static,None,"[sr, c, cf, jd, cs, lr, wh, jr, pm, ap, cy, wt...",NaN,True,NaN,momentum,-0.004680,True,False,0.313100,None,3,NaN,12.0,eval_1211,-0.014541,-0.074299,2010-01-01,9.109267e+05,NaN,NaN
18,NaN,2018-12-31,5,D,static,None,"[ss, al, cu, pb, wr, zn, ni, hc, au, ag, sn]",NaN,True,NaN,momentum,0.000460,True,True,0.253000,None,None,NaN,24.0,eval_1211,0.009753,0.007299,2010-01-01,9.329964e+05,NaN,NaN
19,NaN,2018-12-31,10,D,static,None,"[sr, c, cf, jd, cs, lr, wh, jr, pm, ap, cy, wt...",NaN,True,NaN,momentum,0.005697,True,False,0.170853,None,3,NaN,6.0,eval_1211,0.011254,0.090441,2010-01-01,7.508733e+05,NaN,NaN
20,NaN,2018-12-31,10,D,static,None,"[sr, c, cf, jd, cs, lr, wh, jr, pm, ap, cy, wt...",NaN,True,NaN,momentum,0.005697,True,False,0.170853,None,3,NaN,12.0,eval_1211,0.011254,0.090441,2010-01-01,7.508733e+05,NaN,NaN
21,NaN,2018-12-31,10,D,static,None,"[sr, c, cf, jd, cs, lr, wh, jr, pm, ap, cy, wt...",NaN,True,NaN,momentum,0.005697,True,False,0.170853,None,3,NaN,24.0,eval_1211,0.011254,0.090441,2010-01-01,7.508733e+05,NaN,NaN
22,NaN,2018-12-31,10,D,static,None,"[sr, c, cf, jd, cs, lr, wh, jr, pm, ap, cy, wt...",NaN,True,NaN,momentum,-0.004680,True,False,0.313100,None,3,NaN,24.0,eval_1211,-0.014541,-0.074299,2010-01-01,9.109267e+05,NaN,NaN
23,NaN,2018-12-31,5,D,static,None,"[t, ts, ih, if, tf, ic]",NaN,True,NaN,momentum,0.022126,True,True,0.271557,None,None,NaN,6.0,eval_1211,0.097712,0.351235,2010-01-01,1.741489e+06,NaN,NaN
24,NaN,2018-12-31,5,D,static,None,"[t, ts, ih, if, tf, ic]",NaN,True,NaN,momentum,0.022126,True,True,0.271557,None,None,NaN,12.0,eval_1211,0.097712,0.351235,2010-01-01,1.741489e+06,NaN,NaN
25,NaN,2018-12-31,5,D,static,None,"[t, ts, ih, if, tf, ic]",NaN,True,NaN,momentum,0.022126,True,True,0.271557,None,None,NaN,24.0,eval_1211,0.097712,0.351235,2010-01-01,1.741489e+06,NaN,NaN
26,NaN,2018-12-31,5,D,static,None,"[ss, al, cu, pb, wr, zn, ni, hc, au, ag, sn]",NaN,True,NaN,momentum,0.000460,True,True,0.253000,None,None,NaN,6.0,eval_1211,0.009753,0.007299,2010-01-01,9.329964e+05,NaN,NaN
27,NaN,2018-12-31,5,D,static,None,"[ss, al, cu, pb, wr, zn, ni, hc, au, ag, sn]",NaN,True,NaN,momentum,0.000460,True,True,0.253000,None,None,NaN,12.0,eval_1211,0.009753,0.007299,2010-01-01,9.329964e+05,NaN,NaN
28,0.10,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.055764,True,False,0.117536,None,1,30.0,NaN,eval_1211,0.158034,0.885227,2010-01-01,9.431770e+05,0.10,False
29,0.10,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.039365,True,False,0.176434,None,1,60.0,NaN,eval_1211,0.121745,0.624892,2010-01-01,9.107598e+05,0.10,False
30,0.10,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.054464,True,False,0.157314,None,1,15.0,NaN,eval_1211,0.166836,0.864583,2010-01-01,9.851781e+05,0.10,False
31,0.15,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.053916,True,False,0.097382,None,1,30.0,NaN,eval_1211,0.128680,0.855894,2010-01-01,7.876990e+05,0.15,False
32,0.10,2018-12-31,50,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.037937,True,True,0.126839,None,None,15.0,NaN,eval_1211,0.123657,0.602227,2010-01-01,9.060647e+05,0.10,False
33,0.15,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.051917,True,True,0.095287,None,None,45.0,NaN,eval_1211,0.132840,0.824152,2010-01-01,7.191646e+05,0.15,False
34,0.15,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.048351,True,False,0.099902,None,1,45.0,NaN,eval_1211,0.117564,0.767544,2010-01-01,7.614353e+05,0.15,False
35,0.10,2018-12-31,50,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,NaN,open_interest,0.038655,True,False,0.140498,None,1,15.0,NaN,eval_1211,0.119091,0.613622,2010-01-01,9.041007e+05,0.10,False
36,0.10,2018-12-31,50,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.048917,True,False,0.141344,None,1,15.0,NaN,eval_1211,0.147724,0.776534,2010-01-01,9.631595e+05,0.10,False
37,NaN,2018-12-31,30,D,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",None,NaN,True,NaN,term_structure,0.084001,True,False,0.200072,None,3,NaN,NaN,eval_1211,0.254620,1.333470,2010-01-01,1.060385e+06,NaN,NaN
38,NaN,2018-12-31,30,D,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",None,NaN,True,NaN,term_structure,0.097498,True,False,0.179154,None,3,NaN,NaN,eval_1211,0.260501,1.547727,2010-01-01,9.044683e+05,NaN,NaN
39,NaN,2018-12-31,30,D,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",None,NaN,True,NaN,term_structure,0.100918,True,False,0.153475,None,3,NaN,NaN,eval_1211,0.261648,1.602030,2010-01-01,8.844195e+05,NaN,NaN
40,NaN,2018-12-31,30,D,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",None,NaN,True,NaN,term_structure,0.093832,True,False,0.177011,None,3,NaN,NaN,eval_1211,0.238170,1.489545,2010-01-01,8.510049e+05,NaN,NaN
41,NaN,2018-12-31,30,D,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",None,NaN,True,NaN,term_structure,0.093832,True,False,0.177011,None,3,NaN,NaN,eval_1211,0.238170,1.489545,2010-01-01,8.510049e+05,NaN,NaN
42,NaN,2018-12-31,30,D,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",None,NaN,True,NaN,term_structure,0.100918,True,False,0.153475,None,3,NaN,NaN,eval_1211,0.261648,1.602030,2010-01-01,8.844195e+05,NaN,NaN

## classify the parameters

In [6]:
param_df.columns

Index(['bottom', 'end_date', 'freq', 'freq_unit', 'fut_pool_gen_method',
       'fut_pool_gen_param', 'future_pool', 'if_check_vol', 'if_save_res',
       'index_col', 'indicator_cal_method', 'ir', 'is_main_contract_indi',
       'is_main_contract_op', 'max_drawdown', 'n_nearest_index_indi',
       'n_nearest_index_op', 'num_days', 'num_durations', 'res_dir', 'returns',
       'sharpe', 'start_date', 'std', 'top', 'weighted'],
      dtype='object')

In [7]:
param_df.shape

(43, 26)

In [8]:
param_df

,bottom,end_date,freq,freq_unit,fut_pool_gen_method,fut_pool_gen_param,future_pool,if_check_vol,if_save_res,index_col,indicator_cal_method,ir,is_main_contract_indi,is_main_contract_op,max_drawdown,n_nearest_index_indi,n_nearest_index_op,num_days,num_durations,res_dir,returns,sharpe,start_date,std,top,weighted
0,0.10,2018-12-31,10,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,NaN,hedging_pressure,-0.007226,True,False,0.294970,None,1,15.0,NaN,eval_1211,0.004394,-0.114715,2010-01-01,8.476581e+05,0.10,False
1,0.10,2018-12-31,50,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,hedging_pressure,0.017185,True,True,0.181274,None,None,45.0,NaN,eval_1211,0.032458,0.272801,2010-01-01,8.273289e+05,0.10,False
2,0.10,2018-12-31,10,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,hedging_pressure,-0.000738,True,True,0.289065,None,None,120.0,NaN,eval_1211,0.011090,-0.011718,2010-01-01,8.782764e+05,0.10,False
3,0.15,2018-12-31,10,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,NaN,hedging_pressure,0.008852,True,False,0.200350,None,1,15.0,NaN,eval_1211,0.037052,0.140515,2010-01-01,7.020438e+05,0.15,False
4,0.15,2018-12-31,10,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,m2m,inflation,0.035277,True,False,0.256491,None,1,15.0,20.0,eval_1211,0.098471,0.560003,2010-01-01,9.892406e+05,0.15,False
5,0.20,2018-12-31,10,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,m2m,inflation,0.053705,True,False,0.216983,None,1,15.0,20.0,eval_1211,0.135757,0.852534,2010-01-01,8.426286e+05,0.20,False
6,0.10,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.052697,True,False,0.258388,None,1,15.0,60.0,eval_1211,0.144502,0.836535,2010-01-01,1.239022e+06,0.10,False
7,0.15,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.028922,True,False,0.312836,None,1,15.0,40.0,eval_1211,0.070946,0.459126,2010-01-01,9.937017e+05,0.15,False
8,0.15,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,y2y_1,inflation,0.059496,True,False,0.176823,None,1,15.0,60.0,eval_1211,0.135429,0.944466,2010-01-01,1.052019e+06,0.15,False
9,0.15,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.069659,True,False,0.174384,None,1,15.0,60.0,eval_1211,0.131828,1.105802,2010-01-01,9.929405e+05,0.15,False
10,0.10,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,y2y_1,inflation,0.004788,True,False,0.263905,None,1,15.0,40.0,eval_1211,0.097428,0.076008,2010-01-01,1.331611e+06,0.10,False
11,0.10,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.014572,True,False,0.296795,None,1,15.0,40.0,eval_1211,0.139926,0.231321,2010-01-01,1.305272e+06,0.10,False
12,0.10,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.032485,True,True,0.256667,None,None,15.0,40.0,eval_1211,0.102729,0.515690,2010-01-01,1.250326e+06,0.10,False
13,0.10,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.029908,True,False,0.365413,None,1,15.0,40.0,eval_1211,0.116501,0.474774,2010-01-01,1.233906e+06,0.10,False
14,0.10,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,y2y_1,inflation,0.060348,True,True,0.212514,None,None,15.0,60.0,eval_1211,0.166163,0.957991,2010-01-01,1.314543e+06,0.10,False
15,0.10,2018-12-31,20,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,y2y_1,inflation,0.053105,True,False,0.231606,None,1,15.0,60.0,eval_1211,0.175981,0.843024,2010-01-01,1.281796e+06,0.10,False
16,NaN,2018-12-31,10,D,static,None,"[sr, c, cf, jd, cs, lr, wh, jr, pm, ap, cy, wt...",NaN,True,NaN,momentum,-0.004680,True,False,0.313100,None,3,NaN,6.0,eval_1211,-0.014541,-0.074299,2010-01-01,9.109267e+05,NaN,NaN
17,NaN,2018-12-31,10,D,static,None,"[sr, c, cf, jd, cs, lr, wh, jr, pm, ap, cy, wt...",NaN,True,NaN,momentum,-0.004680,True,False,0.313100,None,3,NaN,12.0,eval_1211,-0.014541,-0.074299,2010-01-01,9.109267e+05,NaN,NaN
18,NaN,2018-12-31,5,D,static,None,"[ss, al, cu, pb, wr, zn, ni, hc, au, ag, sn]",NaN,True,NaN,momentum,0.000460,True,True,0.253000,None,None,NaN,24.0,eval_1211,0.009753,0.007299,2010-01-01,9.329964e+05,NaN,NaN
19,NaN,2018-12-31,10,D,static,None,"[sr, c, cf, jd, cs, lr, wh, jr, pm, ap, cy, wt...",NaN,True,NaN,momentum,0.005697,True,False,0.170853,None,3,NaN,6.0,eval_1211,0.011254,0.090441,2010-01-01,7.508733e+05,NaN,NaN
20,NaN,2018-12-31,10,D,static,None,"[sr, c, cf, jd, cs, lr, wh, jr, pm, ap, cy, wt...",NaN,True,NaN,momentum,0.005697,True,False,0.170853,None,3,NaN,12.0,eval_1211,0.011254,0.090441,2010-01-01,7.508733e+05,NaN,NaN
21,NaN,2018-12-31,10,D,static,None,"[sr, c, cf, jd, cs, lr, wh, jr, pm, ap, cy, wt...",NaN,True,NaN,momentum,0.005697,True,False,0.170853,None,3,NaN,24.0,eval_1211,0.011254,0.090441,2010-01-01,7.508733e+05,NaN,NaN
22,NaN,2018-12-31,10,D,static,None,"[sr, c, cf, jd, cs, lr, wh, jr, pm, ap, cy, wt...",NaN,True,NaN,momentum,-0.004680,True,False,0.313100,None,3,NaN,24.0,eval_1211,-0.014541,-0.074299,2010-01-01,9.109267e+05,NaN,NaN
23,NaN,2018-12-31,5,D,static,None,"[t, ts, ih, if, tf, ic]",NaN,True,NaN,momentum,0.022126,True,True,0.271557,None,None,NaN,6.0,eval_1211,0.097712,0.351235,2010-01-01,1.741489e+06,NaN,NaN
24,NaN,2018-12-31,5,D,static,None,"[t, ts, ih, if, tf, ic]",NaN,True,NaN,momentum,0.022126,True,True,0.271557,None,None,NaN,12.0,eval_1211,0.097712,0.351235,2010-01-01,1.741489e+06,NaN,NaN
25,NaN,2018-12-31,5,D,static,None,"[t, ts, ih, if, tf, ic]",NaN,True,NaN,momentum,0.022126,True,True,0.271557,None,None,NaN,24.0,eval_1211,0.097712,0.351235,2010-01-01,1.741489e+06,NaN,NaN
26,NaN,2018-12-31,5,D,static,None,"[ss, al, cu, pb, wr, zn, ni, hc, au, ag, sn]",NaN,True,NaN,momentum,0.000460,True,True,0.253000,None,None,NaN,6.0,eval_1211,0.009753,0.007299,2010-01-01,9.329964e+05,NaN,NaN
27,NaN,2018-12-31,5,D,static,None,"[ss, al, cu, pb, wr, zn, ni, hc, au, ag, sn]",NaN,True,NaN,momentum,0.000460,True,True,0.253000,None,None,NaN,12.0,eval_1211,0.009753,0.007299,2010-01-01,9.329964e+05,NaN,NaN
28,0.10,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.055764,True,False,0.117536,None,1,30.0,NaN,eval_1211,0.158034,0.885227,2010-01-01,9.431770e+05,0.10,False
29,0.10,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.039365,True,False,0.176434,None,1,60.0,NaN,eval_1211,0.121745,0.624892,2010-01-01,9.107598e+05,0.10,False
30,0.10,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.054464,True,False,0.157314,None,1,15.0,NaN,eval_1211,0.166836,0.864583,2010-01-01,9.851781e+05,0.10,False
31,0.15,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.053916,True,False,0.097382,None,1,30.0,NaN,eval_1211,0.128680,0.855894,2010-01-01,7.876990e+05,0.15,False
32,0.10,2018-12-31,50,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.037937,True,True,0.126839,None,None,15.0,NaN,eval_1211,0.123657,0.602227,2010-01-01,9.060647e+05,0.10,False
33,0.15,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.051917,True,True,0.095287,None,None,45.0,NaN,eval_1211,0.132840,0.824152,2010-01-01,7.191646e+05,0.15,False
34,0.15,2018-12-31,30,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.048351,True,False,0.099902,None,1,45.0,NaN,eval_1211,0.117564,0.767544,2010-01-01,7.614353e+05,0.15,False
35,0.10,2018-12-31,50,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,NaN,open_interest,0.038655,True,False,0.140498,None,1,15.0,NaN,eval_1211,0.119091,0.613622,2010-01-01,9.041007e+05,0.10,False
36,0.10,2018-12-31,50,D,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,NaN,open_interest,0.048917,True,False,0.141344,None,1,15.0,NaN,eval_1211,0.147724,0.776534,2010-01-01,9.631595e+05,0.10,False
37,NaN,2018-12-31,30,D,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",None,NaN,True,NaN,term_structure,0.084001,True,False,0.200072,None,3,NaN,NaN,eval_1211,0.254620,1.333470,2010-01-01,1.060385e+06,NaN,NaN
38,NaN,2018-12-31,30,D,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",None,NaN,True,NaN,term_structure,0.097498,True,False,0.179154,None,3,NaN,NaN,eval_1211,0.260501,1.547727,2010-01-01,9.044683e+05,NaN,NaN
39,NaN,2018-12-31,30,D,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",None,NaN,True,NaN,term_structure,0.100918,True,False,0.153475,None,3,NaN,NaN,eval_1211,0.261648,1.602030,2010-01-01,8.844195e+05,NaN,NaN
40,NaN,2018-12-31,30,D,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",None,NaN,True,NaN,term_structure,0.093832,True,False,0.177011,None,3,NaN,NaN,eval_1211,0.238170,1.489545,2010-01-01,8.510049e+05,NaN,NaN
41,NaN,2018-12-31,30,D,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",None,NaN,True,NaN,term_structure,0.093832,True,False,0.177011,None,3,NaN,NaN,eval_1211,0.238170,1.489545,2010-01-01,8.510049e+05,NaN,NaN
42,NaN,2018-12-31,30,D,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",None,NaN,True,NaN,term_structure,0.100918,True,False,0.153475,None,3,NaN,NaN,eval_1211,0.261648,1.602030,2010-01-01,8.844195e+05,NaN,NaN

In [9]:
param_df.loc[37, "fut_pool_gen_param"]

{'type_list': ['能化', '金属'],
 'cal_method': 'single',
 'method_param': {'time_range': 120,
  'method': 'liquidity',
  'start_date': datetime.datetime(2010, 1, 1, 0, 0),
  'end_date': datetime.datetime(2018, 12, 31, 0, 0),
  'freq': 30,
  'freq_unit': 'D',
  'future_pool': ['ru',
   'sc',
   'tc',
   'zc',
   'l',
   'ta',
   'pp',
   'bu',
   'ma',
   'fu',
   'me',
   'eg',
   'sp',
   'nr',
   'eb',
   'ur',
   'ss',
   'al',
   'cu',
   'pb',
   'wr',
   'zn',
   'ni',
   'hc',
   'au',
   'ag',
   'sn'],
  'is_main_contract_indi': True},
 'sel_fut_param': {'lower_bound': 1,
  'upper_bound': 4,
  'if_use_amount': True,
  'total_num': 10,
  'percent': 0.5},
 'method_2_param': {'time_range': 30, 'method': 'liquidity'},
 'start_date': datetime.datetime(2010, 1, 1, 0, 0),
 'end_date': datetime.datetime(2018, 12, 31, 0, 0),
 'freq_unit': 'D',
 'freq': 30}

In [10]:
alpha_elements = ['index_col', 'is_main_contract_indi',  'n_nearest_index_indi', 'num_days', 'num_durations',  'indicator_cal_method', 'freq', 'freq_unit' ]

In [11]:
for key, group in param_df[alpha_elements].groupby(["indicator_cal_method"]):  
    print(key)
    group = group.drop_duplicates(subset = ['index_col', 'is_main_contract_indi',  'n_nearest_index_indi', 'num_days', 'num_durations', 'freq'], keep = "first")
    print(group)

hedging_pressure
  index_col  is_main_contract_indi n_nearest_index_indi  num_days  \
0       NaN                   True                 None      15.0
1       NaN                   True                 None      45.0
2       NaN                   True                 None     120.0

   num_durations indicator_cal_method  freq freq_unit
0            NaN     hedging_pressure    10         D
1            NaN     hedging_pressure    50         D
2            NaN     hedging_pressure    10         D
inflation
   index_col  is_main_contract_indi n_nearest_index_indi  num_days  \
4        m2m                   True                 None      15.0
6      y2y_1                   True                 None      15.0
7      y2y_1                   True                 None      15.0
10     y2y_1                   True                 None      15.0

    num_durations indicator_cal_method  freq freq_unit
4            20.0            inflation    10         D
6            60.0            inflation    20         D
7            40.0            inflation    30         D
10           40.0            inflation    20         D
momentum
   index_col  is_main_contract_indi n_nearest_index_indi  num_days  \
16       NaN                   True                 None       NaN
17       NaN                   True                 None       NaN
18       NaN                   True                 None       NaN
21       NaN                   True                 None       NaN
23       NaN                   True                 None       NaN
24       NaN                   True                 None       NaN

    num_durations indicator_cal_method  freq freq_unit
16            6.0             momentum    10         D
17           12.0             momentum    10         D
18           24.0             momentum     5         D
21           24.0             momentum    10         D
23            6.0             momentum     5         D
24           12.0             momentum     5         D
open_interest
   index_col  is_main_contract_indi n_nearest_index_indi  num_days  \
28       NaN                   True                 None      30.0
29       NaN                   True                 None      60.0
30       NaN                   True                 None      15.0
32       NaN                   True                 None      15.0
33       NaN                   True                 None      45.0

    num_durations indicator_cal_method  freq freq_unit
28            NaN        open_interest    30         D
29            NaN        open_interest    30         D
30            NaN        open_interest    30         D
32            NaN        open_interest    50         D
33            NaN        open_interest    30         D
term_structure
   index_col  is_main_contract_indi n_nearest_index_indi  num_days  \
37       NaN                   True                 None       NaN

    num_durations indicator_cal_method  freq freq_unit
37            NaN       term_structure    30         D

## create data proxy

In [12]:
from DB_Future import FutureDatabase

db_name = 'ultralpha_db'
host_name = '192.168.0.116'
user = 'cyr'
password = 'cyr'
port = '5432'
fut_name = 'al'
start_date = '2010-04-01'
end_date = '2018-12-31'

database = FutureDatabase(db_name = db_name,host_name = host_name, user_name = user, pwd = password,
                          port = port )

Future Database init...
Time used: 42.6083995

In [13]:
start_date = datetime.datetime(2010, 1, 1)
end_date = datetime.datetime(2019,12, 31)
time_df = database.get_daily_df(start_date = start_date, end_date = end_date)
time_df = time_df[["instrument"]]

In [14]:
time_df = time_df.reset_index().drop_duplicates(subset = ["date", "instrument"], keep = "first").set_index(["date"])

In [15]:
time_df.shape[0]

94478

In [16]:
time_df[:100]

           instrument
date
2010-01-04         rb
2010-01-04         ro
2010-01-04          p
2010-01-04         sr
2010-01-04         ru
2010-01-04         ws
2010-01-04          a
2010-01-04         ta
2010-01-04          c
2010-01-04         au
2010-01-04          b
2010-01-04         cu
2010-01-04         cf
2010-01-04          l
2010-01-04         al
2010-01-04         fu
2010-01-04         er
2010-01-04          y
2010-01-04         wt
2010-01-04          m
2010-01-04         zn
2010-01-04          v
2010-01-04         wr
2010-01-04         gn
2010-01-05         rb
2010-01-05          m
2010-01-05         ru
2010-01-05          c
2010-01-05          l
2010-01-05         er
2010-01-05         au
2010-01-05         fu
2010-01-05         cu
2010-01-05         wr
2010-01-05          v
2010-01-05         ro
2010-01-05          p
2010-01-05         ws
2010-01-05         wt
2010-01-05         ta
2010-01-05          y
2010-01-05         cf
2010-01-05         al
2010-01-05          b
2010-01-05          a
2010-01-05         zn
2010-01-05         sr
2010-01-05         gn
2010-01-06          m
2010-01-06         ta
2010-01-06         fu
2010-01-06         cf
2010-01-06         au
2010-01-06          b
2010-01-06         sr
2010-01-06          l
2010-01-06         gn
2010-01-06          c
2010-01-06         rb
2010-01-06         ru
2010-01-06         cu
2010-01-06         ro
2010-01-06          p
2010-01-06          v
2010-01-06         wt
2010-01-06         zn
2010-01-06          y
2010-01-06          a
2010-01-06         al
2010-01-06         wr
2010-01-06         ws
2010-01-06         er
2010-01-07         er
2010-01-07          b
2010-01-07          l
2010-01-07         sr
2010-01-07         fu
2010-01-07         au
2010-01-07         ro
2010-01-07         zn
2010-01-07         cf
2010-01-07          p
2010-01-07         cu
2010-01-07          m
2010-01-07         ru
2010-01-07          a
2010-01-07         al
2010-01-07         gn
2010-01-07         wt
2010-01-07          y
2010-01-07         rb
2010-01-07          c
2010-01-07         wr
2010-01-07         ta
2010-01-07         ws
2010-01-07          v
2010-01-08         rb
2010-01-08         fu
2010-01-08         ta
2010-01-08          l

In [17]:
indi_generator =  IndicatorGenerator(database)

### hedge pressure

In [16]:
# start_date = datetime.datetime(2010, 1, 1)
# end_date = datetime.datetime(2019, 12, 31)

In [17]:
# hp_param = param_df[param_df["indicator_cal_method"] == "hedging_pressure"]

In [18]:
# hp_param = hp_param[alpha_elements]
# indi_list = []
# for i in hp_param.index:
#     param = hp_param.loc[i]
# #     for index in param.index:
# #         print(param[index])
#     param_dic = {index: param[index] for index in param.index}
#     param_dic["method"] = param_dic.pop("indicator_cal_method")
#     param_dic["start_date"] = start_date
#     param_dic["end_date"] = end_date
#     param_dic["future_pool"] = None
#     param_dic["freq_unit"] = "D"
#     print(param_dic)
#     print(" " * 7)
#     indi = indi_generator.cal_indicator(param_dic)
#     indi_list.append(indi)
# #     print(indi)
#     #     date

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 15.0, 'num_durations': nan, 'freq': 10, 'freq_unit': 'D', 'method': 'hedging_pressure', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}

Calculate hedging pressure
freq 10
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 10 date length 2286
2009-11-24 12:00:00 2010-01-04 00:00:00
freq 10 date length 28
Time for calculating hedging pressure 26.810322523117065
{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 45.0, 'num_durations': nan, 'freq': 50, 'freq_unit': 'D', 'method': 'hedging_pressure', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}

Calculate hedging pressure
freq 50
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 50 date length 2286
2009-09-10 12:00:00 2010-01-04 00:00:00
freq 50 date length 75
Time for calculating hedging pressure 18.082656383514404
{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 120.0, 'num_durations': nan, 'freq': 10, 'freq_unit': 'D', 'method': 'hedging_pressure', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}

Calculate hedging pressure
freq 10
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 10 date length 2286
2009-03-07 00:00:00 2010-01-04 00:00:00
freq 10 date length 205
Time for calculating hedging pressure 27.722883701324463
{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 15.0, 'num_durations': nan, 'freq': 10, 'freq_unit': 'D', 'method': 'hedging_pressure', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}

Calculate hedging pressure
freq 10
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 10 date length 2286
2009-11-24 12:00:00 2010-01-04 00:00:00
freq 10 date length 28
Time for calculating hedging pressure 26.59689450263977

In [23]:
pd.merge(indi_list[0], time_df.reset_index(), on = ["date", "instrument"] ,  how = "outer" )[:200]

    instrument       date  indicator
0            a 2010-01-04  -0.010400
1           al 2010-01-04   0.003555
2           au 2010-01-04   0.022792
3            b 2010-01-04   0.010490
4            c 2010-01-04   0.085571
5           cu 2010-01-04  -0.000261
6           fu 2010-01-04  -0.010541
7            l 2010-01-04   0.006867
8            m 2010-01-04   0.001691
9            p 2010-01-04   0.019525
10          rb 2010-01-04   0.004284
11          ru 2010-01-04   0.001691
12           v 2010-01-04  -0.002988
13          wr 2010-01-04   0.138033
14           y 2010-01-04   0.001179
15          zn 2010-01-04   0.002061
16           a 2010-01-18  -0.004824
17          al 2010-01-18   0.019676
18          au 2010-01-18  -0.023477
19           b 2010-01-18   0.053498
20           c 2010-01-18   0.034444
21          cu 2010-01-18   0.002185
22          fu 2010-01-18   0.024569
23           l 2010-01-18  -0.007089
24           m 2010-01-18   0.002822
25           p 2010-01-18   0.009365
26          rb 2010-01-18  -0.000676
27          ru 2010-01-18   0.009284
28           v 2010-01-18  -0.047919
29          wr 2010-01-18   0.200755
30           y 2010-01-18   0.002444
31          zn 2010-01-18   0.002078
32           a 2010-02-01   0.002422
33          al 2010-02-01  -0.012818
34          au 2010-02-01  -0.063103
35           b 2010-02-01   0.066390
36           c 2010-02-01  -0.084949
37          cu 2010-02-01   0.027563
38          fu 2010-02-01  -0.000585
39           l 2010-02-01   0.001772
40           m 2010-02-01   0.005213
41           p 2010-02-01   0.000734
42          rb 2010-02-01  -0.004264
43          ru 2010-02-01  -0.001348
44           v 2010-02-01  -0.001367
45          wr 2010-02-01   0.151532
46           y 2010-02-01   0.007677
47          zn 2010-02-01   0.007654
48           a 2010-02-22  -0.006225
49          al 2010-02-22  -0.004719
50          au 2010-02-22  -0.075133
51           b 2010-02-22  -0.047521
52           c 2010-02-22  -0.066615
53          cu 2010-02-22  -0.011429
54          fu 2010-02-22  -0.031854
55           l 2010-02-22  -0.007436
56           m 2010-02-22  -0.018194
57           p 2010-02-22   0.000795
58          rb 2010-02-22  -0.009940
59          ru 2010-02-22  -0.003792
60           v 2010-02-22  -0.017518
61          wr 2010-02-22   0.012717
62           y 2010-02-22  -0.026778
63          zn 2010-02-22  -0.005440
64           a 2010-03-08  -0.002000
65          al 2010-03-08   0.010038
66          au 2010-03-08   0.021597
67           b 2010-03-08  -0.121019
68           c 2010-03-08  -0.025988
69          cu 2010-03-08   0.004732
70          fu 2010-03-08  -0.045179
71           l 2010-03-08   0.017400
72           m 2010-03-08   0.005640
73           p 2010-03-08   0.001735
74          rb 2010-03-08  -0.005969
75          ru 2010-03-08   0.002158
76           v 2010-03-08   0.019018
77          wr 2010-03-08   0.008881
78           y 2010-03-08  -0.011814
79          zn 2010-03-08   0.001136
80           a 2010-03-22  -0.013873
81          al 2010-03-22   0.020064
82          au 2010-03-22   0.000505
83           b 2010-03-22   0.098497
84           c 2010-03-22   0.053089
85          cu 2010-03-22  -0.009906
86          fu 2010-03-22  -0.033148
87           l 2010-03-22   0.009515
88           m 2010-03-22   0.000887
89           p 2010-03-22  -0.009216
90          rb 2010-03-22   0.026865
91          ru 2010-03-22   0.004674
92           v 2010-03-22  -0.005918
93          wr 2010-03-22  -0.129623
94           y 2010-03-22  -0.006138
95          zn 2010-03-22   0.000003
96           a 2010-04-06  -0.026836
97          al 2010-04-06  -0.020667
98          au 2010-04-06  -0.048043
99           b 2010-04-06   0.046997
100          c 2010-04-06   0.037883
101         cu 2010-04-06   0.004560
102         fu 2010-04-06   0.028054
103          l 2010-04-06  -0.009716
104          m 2010-04-06  -0.005383
105          p 2010-04-06  -0.010778
106         rb 2010-04-06   0.009418
107         ru 2010-04-06   0.000848
108          v 2010-04-06  -0.030975
109         wr 2010-04-06  -0.066380
110          y 2010-04-06  -0.002502
111         zn 2010-04-06   0.004913
112          a 2010-04-20  -0.036704
113         al 2010-04-20   0.053271
114         au 2010-04-20  -0.064406
115          b 2010-04-20  -0.035011
116          c 2010-04-20   0.007528
117         cu 2010-04-20  -0.001327
118         fu 2010-04-20  -0.068581
119          l 2010-04-20   0.001744
120          m 2010-04-20  -0.036812
121          p 2010-04-20  -0.013139
122         rb 2010-04-20   0.006218
123         ru 2010-04-20   0.000391
124          v 2010-04-20   0.087308
125         wr 2010-04-20  -0.021783
126          y 2010-04-20  -0.068971
127         zn 2010-04-20   0.004635
128          a 2010-05-05   0.041732
129         al 2010-05-05  -0.122702
130         au 2010-05-05   0.063620
131          b 2010-05-05  -0.143210
132          c 2010-05-05   0.035662
133         cu 2010-05-05  -0.013403
134         fu 2010-05-05  -0.113381
135          l 2010-05-05   0.003469
136          m 2010-05-05   0.038771
137          p 2010-05-05  -0.017985
138         rb 2010-05-05  -0.000347
139         ru 2010-05-05  -0.001872
140          v 2010-05-05   0.008644
141         wr 2010-05-05  -0.137880
142          y 2010-05-05   0.053637
143         zn 2010-05-05  -0.012978
144          a 2010-05-19   0.014015
145         al 2010-05-19   0.033214
146         au 2010-05-19   0.023090
147          b 2010-05-19  -0.201439
148          c 2010-05-19   0.015485
149         cu 2010-05-19   0.011072
150         fu 2010-05-19   0.102034
151         if 2010-05-19   0.003385
152          l 2010-05-19  -0.002698
153          m 2010-05-19   0.002484
154          p 2010-05-19   0.011428
155         rb 2010-05-19  -0.006024
156         ru 2010-05-19   0.000294
157          v 2010-05-19  -0.020892
158         wr 2010-05-19  -0.048287
159          y 2010-05-19  -0.009800
160         zn 2010-05-19   0.011311
161          a 2010-06-02   0.003223
162         al 2010-06-02  -0.010799
163         au 2010-06-02  -0.007508
164          b 2010-06-02   0.140930
165          c 2010-06-02  -0.081082
166         cu 2010-06-02  -0.003162
167         fu 2010-06-02   0.069609
168         if 2010-06-02  -0.000851
169          l 2010-06-02  -0.000461
170          m 2010-06-02   0.002014
171          p 2010-06-02   0.007686
172         rb 2010-06-02  -0.000880
173         ru 2010-06-02   0.000290
174          v 2010-06-02  -0.016507
175         wr 2010-06-02  -0.053996
176          y 2010-06-02  -0.005458
177         zn 2010-06-02   0.005194
178          a 2010-06-21  -0.016695
179         al 2010-06-21   0.043373
180         au 2010-06-21   0.019543
181          b 2010-06-21  -0.280392
182          c 2010-06-21   0.016652
183         cu 2010-06-21   0.008435
184         fu 2010-06-21  -0.015655
185         if 2010-06-21   0.023063
186          l 2010-06-21   0.006612
187          m 2010-06-21  -0.010221
188          p 2010-06-21  -0.004401
189         rb 2010-06-21  -0.002861
190         ru 2010-06-21  -0.002438
191          v 2010-06-21  -0.021729
192         wr 2010-06-21  -0.020054
193          y 2010-06-21  -0.001410
194         zn 2010-06-21   0.003297
195          a 2010-07-05  -0.024906
196         al 2010-07-05  -0.042350
197         au 2010-07-05  -0.008454
198          b 2010-07-05   0.035714
199          c 2010-07-05   0.011987

# create the alpha table

In [18]:
cal_indi_param_df = param_df[alpha_elements]
cal_indi_param_df = cal_indi_param_df.rename(columns = {"indicator_cal_method": "method"})
cal_indi_param_df["alpha_id"] = cal_indi_param_df["method"]
cal_indi_param_df

,index_col,is_main_contract_indi,n_nearest_index_indi,num_days,num_durations,method,freq,freq_unit,alpha_id
0,NaN,True,None,15.0,NaN,hedging_pressure,10,D,hedging_pressure
1,NaN,True,None,45.0,NaN,hedging_pressure,50,D,hedging_pressure
2,NaN,True,None,120.0,NaN,hedging_pressure,10,D,hedging_pressure
3,NaN,True,None,15.0,NaN,hedging_pressure,10,D,hedging_pressure
4,m2m,True,None,15.0,20.0,inflation,10,D,inflation
5,m2m,True,None,15.0,20.0,inflation,10,D,inflation
6,y2y_1,True,None,15.0,60.0,inflation,20,D,inflation
7,y2y_1,True,None,15.0,40.0,inflation,30,D,inflation
8,y2y_1,True,None,15.0,60.0,inflation,20,D,inflation
9,y2y_1,True,None,15.0,60.0,inflation,20,D,inflation
10,y2y_1,True,None,15.0,40.0,inflation,20,D,inflation
11,y2y_1,True,None,15.0,40.0,inflation,20,D,inflation
12,y2y_1,True,None,15.0,40.0,inflation,30,D,inflation
13,y2y_1,True,None,15.0,40.0,inflation,30,D,inflation
14,y2y_1,True,None,15.0,60.0,inflation,20,D,inflation
15,y2y_1,True,None,15.0,60.0,inflation,20,D,inflation
16,NaN,True,None,NaN,6.0,momentum,10,D,momentum
17,NaN,True,None,NaN,12.0,momentum,10,D,momentum
18,NaN,True,None,NaN,24.0,momentum,5,D,momentum
19,NaN,True,None,NaN,6.0,momentum,10,D,momentum
20,NaN,True,None,NaN,12.0,momentum,10,D,momentum
21,NaN,True,None,NaN,24.0,momentum,10,D,momentum
22,NaN,True,None,NaN,24.0,momentum,10,D,momentum
23,NaN,True,None,NaN,6.0,momentum,5,D,momentum
24,NaN,True,None,NaN,12.0,momentum,5,D,momentum
25,NaN,True,None,NaN,24.0,momentum,5,D,momentum
26,NaN,True,None,NaN,6.0,momentum,5,D,momentum
27,NaN,True,None,NaN,12.0,momentum,5,D,momentum
28,NaN,True,None,30.0,NaN,open_interest,30,D,open_interest
29,NaN,True,None,60.0,NaN,open_interest,30,D,open_interest
30,NaN,True,None,15.0,NaN,open_interest,30,D,open_interest
31,NaN,True,None,30.0,NaN,open_interest,30,D,open_interest
32,NaN,True,None,15.0,NaN,open_interest,50,D,open_interest
33,NaN,True,None,45.0,NaN,open_interest,30,D,open_interest
34,NaN,True,None,45.0,NaN,open_interest,30,D,open_interest
35,NaN,True,None,15.0,NaN,open_interest,50,D,open_interest
36,NaN,True,None,15.0,NaN,open_interest,50,D,open_interest
37,NaN,True,None,NaN,NaN,term_structure,30,D,term_structure
38,NaN,True,None,NaN,NaN,term_structure,30,D,term_structure
39,NaN,True,None,NaN,NaN,term_structure,30,D,term_structure
40,NaN,True,None,NaN,NaN,term_structure,30,D,term_structure
41,NaN,True,None,NaN,NaN,term_structure,30,D,term_structure
42,NaN,True,None,NaN,NaN,term_structure,30,D,term_structure

In [19]:
alpha_dic = {"hedging_pressure": "hp",
             "inflation": "in",
             "momentum": "mom",
             "open_interest": "oi",
             "term_structure": "ts"}

In [20]:
cal_indi_param_df["alpha_id"] = cal_indi_param_df["alpha_id"].map(alpha_dic)

In [21]:
cal_indi_param_df = cal_indi_param_df.drop_duplicates(subset = cal_indi_param_df.columns)

In [22]:
def assign(sub_df):
    sub_df["id"] = np.arange(sub_df.shape[0])
    return sub_df 

cal_indi_param_df = cal_indi_param_df.groupby(["method"]).apply(assign)

In [23]:
cal_indi_param_df["alpha_id"] = cal_indi_param_df.apply(lambda r:r["alpha_id"] +   "-" + str(r["id"]), axis=1 )
cal_indi_param_df = cal_indi_param_df.drop(columns = ["id"])

In [24]:
for col in ["num_days", "num_durations", "freq"]:
    cal_indi_param_df[col] = cal_indi_param_df[col].map(lambda x: int(x) if not np.isnan(x) else x)
# cal_indi_param_df["freq"] = cal_indi_param_df["freq"].map(lambda x: np.asscalar(int(x)) if not np.isnan(x) else x)

In [25]:
print(cal_indi_param_df.shape)

(19, 9)

In [26]:
cal_indi_param_df

,index_col,is_main_contract_indi,n_nearest_index_indi,num_days,num_durations,method,freq,freq_unit,alpha_id
0,NaN,True,None,15.0,NaN,hedging_pressure,10,D,hp-0
1,NaN,True,None,45.0,NaN,hedging_pressure,50,D,hp-1
2,NaN,True,None,120.0,NaN,hedging_pressure,10,D,hp-2
4,m2m,True,None,15.0,20.0,inflation,10,D,in-0
6,y2y_1,True,None,15.0,60.0,inflation,20,D,in-1
7,y2y_1,True,None,15.0,40.0,inflation,30,D,in-2
10,y2y_1,True,None,15.0,40.0,inflation,20,D,in-3
16,NaN,True,None,NaN,6.0,momentum,10,D,mom-0
17,NaN,True,None,NaN,12.0,momentum,10,D,mom-1
18,NaN,True,None,NaN,24.0,momentum,5,D,mom-2
21,NaN,True,None,NaN,24.0,momentum,10,D,mom-3
23,NaN,True,None,NaN,6.0,momentum,5,D,mom-4
24,NaN,True,None,NaN,12.0,momentum,5,D,mom-5
28,NaN,True,None,30.0,NaN,open_interest,30,D,oi-0
29,NaN,True,None,60.0,NaN,open_interest,30,D,oi-1
30,NaN,True,None,15.0,NaN,open_interest,30,D,oi-2
32,NaN,True,None,15.0,NaN,open_interest,50,D,oi-3
33,NaN,True,None,45.0,NaN,open_interest,30,D,oi-4
37,NaN,True,None,NaN,NaN,term_structure,30,D,ts-0

In [27]:
indi_list = []
for i in cal_indi_param_df.index:
    param = cal_indi_param_df.loc[i]
    param_dic = {index: param[index] for index in param.index}
    alpha_id = cal_indi_param_df.loc[i, "alpha_id"]
    param_dic["start_date"] = start_date
    param_dic["end_date"] = end_date
    param_dic["future_pool"] = None
    param_dic["freq"] = param_dic["freq"].item()
    print(param_dic)
#     print(type(param_dic["freq"]))
    indi = indi_generator.cal_indicator(param_dic)
    indi = indi.rename(columns = {"indicator": alpha_id})
    print(" " * 7)
#     print(indi)
    indi_list.append(indi)

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 15.0, 'num_durations': nan, 'method': 'hedging_pressure', 'freq': 10, 'freq_unit': 'D', 'alpha_id': 'hp-0', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculate hedging pressure
freq 10
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 10 date length 2286
2009-11-24 12:00:00 2010-01-04 00:00:00
freq 10 date length 28
Time for calculating hedging pressure 25.011122465133667

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 45.0, 'num_durations': nan, 'method': 'hedging_pressure', 'freq': 50, 'freq_unit': 'D', 'alpha_id': 'hp-1', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculate hedging pressure
freq 50
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 50 date length 2286
2009-09-10 12:00:00 2010-01-04 00:00:00
freq 50 date length 75
Time for calculating hedging pressure 16.906086683273315

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 120.0, 'num_durations': nan, 'method': 'hedging_pressure', 'freq': 10, 'freq_unit': 'D', 'alpha_id': 'hp-2', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculate hedging pressure
freq 10
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 10 date length 2286
2009-03-07 00:00:00 2010-01-04 00:00:00
freq 10 date length 205
Time for calculating hedging pressure 25.978536367416382

{'index_col': 'm2m', 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 15.0, 'num_durations': 20.0, 'method': 'inflation', 'freq': 10, 'freq_unit': 'D', 'alpha_id': 'in-0', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculating inflation
freq 10
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 10 date length 2286
2008-08-19 00:00:00 2010-01-04 00:00:00
freq 10 date length 336
Time for calculating  inflation 37.989442110061646

{'index_col': 'y2y_1', 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 15.0, 'num_durations': 60.0, 'method': 'inflation', 'freq': 20, 'freq_unit': 'D', 'alpha_id': 'in-1', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculating inflation
freq 20
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 20 date length 2286
2001-10-15 00:00:00 2010-01-04 00:00:00
freq 20 date length 1218
Time for calculating  inflation 28.938620567321777

{'index_col': 'y2y_1', 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 15.0, 'num_durations': 40.0, 'method': 'inflation', 'freq': 30, 'freq_unit': 'D', 'alpha_id': 'in-2', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculating inflation
freq 30
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 30 date length 2286
2001-10-15 00:00:00 2010-01-04 00:00:00
freq 30 date length 1218
Time for calculating  inflation 25.121827602386475

{'index_col': 'y2y_1', 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 15.0, 'num_durations': 40.0, 'method': 'inflation', 'freq': 20, 'freq_unit': 'D', 'alpha_id': 'in-3', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculating inflation
freq 20
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 20 date length 2286
2004-07-11 00:00:00 2010-01-04 00:00:00
freq 20 date length 1218
Time for calculating  inflation 29.068274974822998

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': nan, 'num_durations': 6.0, 'method': 'momentum', 'freq': 10, 'freq_unit': 'D', 'alpha_id': 'mom-0', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculate momentum
freq 10
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 10 date length 2286
2009-08-04 00:00:00 2010-01-04 00:00:00
freq 10 date length 103
Time for calculating momentum 34.989442110061646

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': nan, 'num_durations': 12.0, 'method': 'momentum', 'freq': 10, 'freq_unit': 'D', 'alpha_id': 'mom-1', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculate momentum
freq 10
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 10 date length 2286
2009-03-07 00:00:00 2010-01-04 00:00:00
freq 10 date length 205
Time for calculating momentum 36.0326714515686

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': nan, 'num_durations': 24.0, 'method': 'momentum', 'freq': 5, 'freq_unit': 'D', 'alpha_id': 'mom-2', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculate momentum
freq 5
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 5 date length 2286
2009-03-07 00:00:00 2010-01-04 00:00:00
freq 5 date length 205
Time for calculating momentum 59.57871437072754

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': nan, 'num_durations': 24.0, 'method': 'momentum', 'freq': 10, 'freq_unit': 'D', 'alpha_id': 'mom-3', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculate momentum
freq 10
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 10 date length 2286
2008-05-11 00:00:00 2010-01-04 00:00:00
freq 10 date length 406
Time for calculating momentum 36.968119382858276

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': nan, 'num_durations': 6.0, 'method': 'momentum', 'freq': 5, 'freq_unit': 'D', 'alpha_id': 'mom-4', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculate momentum
freq 5
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 5 date length 2286
2009-10-18 00:00:00 2010-01-04 00:00:00
freq 5 date length 55
Time for calculating momentum 56.54181408882141

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': nan, 'num_durations': 12.0, 'method': 'momentum', 'freq': 5, 'freq_unit': 'D', 'alpha_id': 'mom-5', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculate momentum
freq 5
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 5 date length 2286
2009-08-04 00:00:00 2010-01-04 00:00:00
freq 5 date length 103
Time for calculating momentum 58.586299896240234

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 30.0, 'num_durations': nan, 'method': 'open_interest', 'freq': 30, 'freq_unit': 'D', 'alpha_id': 'oi-0', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculating open interest
freq 30
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 30 date length 2286
2009-10-18 00:00:00 2010-01-04 00:00:00
freq 30 date length 55
Time for calculating open interest 18.14360022544861

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 60.0, 'num_durations': nan, 'method': 'open_interest', 'freq': 30, 'freq_unit': 'D', 'alpha_id': 'oi-1', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculating open interest
freq 30
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 30 date length 2286
2009-08-04 00:00:00 2010-01-04 00:00:00
freq 30 date length 103
Time for calculating open interest 18.298173666000366

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 15.0, 'num_durations': nan, 'method': 'open_interest', 'freq': 30, 'freq_unit': 'D', 'alpha_id': 'oi-2', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculating open interest
freq 30
2010-01-01 00:00:00 2019-12-31 00:00:00

freq 30 date length 2286
2009-10-18 00:00:00 2010-01-04 00:00:00
freq 30 date length 55
Time for calculating open interest 18.373842239379883

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 15.0, 'num_durations': nan, 'method': 'open_interest', 'freq': 50, 'freq_unit': 'D', 'alpha_id': 'oi-3', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculating open interest
freq 50
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 50 date length 2286
2009-08-29 00:00:00 2010-01-04 00:00:00
freq 50 date length 84
Time for calculating open interest 16.6644504070282

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': 45.0, 'num_durations': nan, 'method': 'open_interest', 'freq': 30, 'freq_unit': 'D', 'alpha_id': 'oi-4', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculating open interest
freq 30
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 30 date length 2286
2009-09-10 12:00:00 2010-01-04 00:00:00
freq 30 date length 75
Time for calculating open interest 18.346541166305542

{'index_col': nan, 'is_main_contract_indi': True, 'n_nearest_index_indi': None, 'num_days': nan, 'num_durations': nan, 'method': 'term_structure', 'freq': 30, 'freq_unit': 'D', 'alpha_id': 'ts-0', 'start_date': datetime.datetime(2010, 1, 1, 0, 0), 'end_date': datetime.datetime(2019, 12, 31, 0, 0), 'future_pool': None}
Calculate term structure
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 30 date length 2286
2010-01-01 00:00:00 2019-12-31 00:00:00
freq 30 date length 2286
Time for calculating term structure  32.43532419204712

In [28]:
print(len(time_df.copy().reset_index()))

94478

In [29]:
for i in range(len(indi_list)):
    alist = sorted(set(indi_list[i]["date"]))
    print(i, len(alist))

0 229
1 46
2 236
3 242
4 81
5 55
6 101
7 233
8 237
9 474
10 245
11 462
12 466
13 76
14 77
15 77
16 46
17 77
18 77

In [30]:
print(sorted(set(indi_list[14]["date"])))

[Timestamp('2010-01-04 00:00:00'), Timestamp('2010-02-22 00:00:00'), Timestamp('2010-04-06 00:00:00'), Timestamp('2010-05-19 00:00:00'), Timestamp('2010-07-05 00:00:00'), Timestamp('2010-08-16 00:00:00'), Timestamp('2010-09-30 00:00:00'), Timestamp('2010-11-18 00:00:00'), Timestamp('2010-12-30 00:00:00'), Timestamp('2011-02-18 00:00:00'), Timestamp('2011-04-01 00:00:00'), Timestamp('2011-05-18 00:00:00'), Timestamp('2011-06-30 00:00:00'), Timestamp('2011-08-11 00:00:00'), Timestamp('2011-09-23 00:00:00'), Timestamp('2011-11-11 00:00:00'), Timestamp('2011-12-23 00:00:00'), Timestamp('2012-02-14 00:00:00'), Timestamp('2012-03-27 00:00:00'), Timestamp('2012-05-15 00:00:00'), Timestamp('2012-06-27 00:00:00'), Timestamp('2012-08-08 00:00:00'), Timestamp('2012-09-19 00:00:00'), Timestamp('2012-11-07 00:00:00'), Timestamp('2012-12-19 00:00:00'), Timestamp('2013-02-04 00:00:00'), Timestamp('2013-03-25 00:00:00'), Timestamp('2013-05-13 00:00:00'), Timestamp('2013-06-27 00:00:00'), Timestamp('2013-08-08 00:00:00'), Timestamp('2013-09-23 00:00:00'), Timestamp('2013-11-11 00:00:00'), Timestamp('2013-12-23 00:00:00'), Timestamp('2014-02-11 00:00:00'), Timestamp('2014-03-25 00:00:00'), Timestamp('2014-05-09 00:00:00'), Timestamp('2014-06-23 00:00:00'), Timestamp('2014-08-04 00:00:00'), Timestamp('2014-09-16 00:00:00'), Timestamp('2014-11-04 00:00:00'), Timestamp('2014-12-16 00:00:00'), Timestamp('2015-01-29 00:00:00'), Timestamp('2015-03-19 00:00:00'), Timestamp('2015-05-04 00:00:00'), Timestamp('2015-06-15 00:00:00'), Timestamp('2015-07-28 00:00:00'), Timestamp('2015-09-10 00:00:00'), Timestamp('2015-10-29 00:00:00'), Timestamp('2015-12-10 00:00:00'), Timestamp('2016-01-22 00:00:00'), Timestamp('2016-03-11 00:00:00'), Timestamp('2016-04-25 00:00:00'), Timestamp('2016-06-07 00:00:00'), Timestamp('2016-07-21 00:00:00'), Timestamp('2016-09-01 00:00:00'), Timestamp('2016-10-24 00:00:00'), Timestamp('2016-12-05 00:00:00'), Timestamp('2017-01-17 00:00:00'), Timestamp('2017-03-07 00:00:00'), Timestamp('2017-04-20 00:00:00'), Timestamp('2017-06-06 00:00:00'), Timestamp('2017-07-18 00:00:00'), Timestamp('2017-08-29 00:00:00'), Timestamp('2017-10-17 00:00:00'), Timestamp('2017-11-28 00:00:00'), Timestamp('2018-01-10 00:00:00'), Timestamp('2018-02-28 00:00:00'), Timestamp('2018-04-13 00:00:00'), Timestamp('2018-05-29 00:00:00'), Timestamp('2018-07-11 00:00:00'), Timestamp('2018-08-22 00:00:00'), Timestamp('2018-10-11 00:00:00'), Timestamp('2018-11-22 00:00:00'), Timestamp('2019-01-07 00:00:00'), Timestamp('2019-02-25 00:00:00'), Timestamp('2019-04-09 00:00:00'), Timestamp('2019-05-24 00:00:00')]

In [31]:
alpha_df = time_df.copy().reset_index()

for i in range(len(indi_list)):
    alpha_df = pd.merge(indi_list[i], alpha_df, on = ["date", "instrument"] ,  how = "outer" )

In [34]:
# alpha_df[:30]

In [35]:
alpha_data_dir = "alpha_data"
if not os.path.exists(alpha_data_dir):
    os.mkdir(alpha_data_dir)

In [37]:
alpha_df.to_csv("alpha_data" + os.sep + "alpha_df.csv", index = False)

In [55]:
cal_indi_param_df

,index_col,is_main_contract_indi,n_nearest_index_indi,num_days,num_durations,method,freq,freq_unit,alpha_id
0,NaN,True,None,15.0,NaN,hedging_pressure,10,D,hp-0
1,NaN,True,None,45.0,NaN,hedging_pressure,50,D,hp-1
2,NaN,True,None,120.0,NaN,hedging_pressure,10,D,hp-2
4,m2m,True,None,15.0,20.0,inflation,10,D,in-0
6,y2y_1,True,None,15.0,60.0,inflation,20,D,in-1
7,y2y_1,True,None,15.0,40.0,inflation,30,D,in-2
10,y2y_1,True,None,15.0,40.0,inflation,20,D,in-3
16,NaN,True,None,NaN,6.0,momentum,10,D,mom-0
17,NaN,True,None,NaN,12.0,momentum,10,D,mom-1
18,NaN,True,None,NaN,24.0,momentum,5,D,mom-2
21,NaN,True,None,NaN,24.0,momentum,10,D,mom-3
23,NaN,True,None,NaN,6.0,momentum,5,D,mom-4
24,NaN,True,None,NaN,12.0,momentum,5,D,mom-5
28,NaN,True,None,30.0,NaN,open_interest,30,D,oi-0
29,NaN,True,None,60.0,NaN,open_interest,30,D,oi-1
30,NaN,True,None,15.0,NaN,open_interest,30,D,oi-2
32,NaN,True,None,15.0,NaN,open_interest,50,D,oi-3
33,NaN,True,None,45.0,NaN,open_interest,30,D,oi-4
37,NaN,True,None,NaN,NaN,term_structure,30,D,ts-0

In [56]:
cal_indi_param_df.to_csv(alpha_data_dir + os.sep + "alpha_param_df.csv", index = False)

In [58]:
alpha_elements

['index_col',
 'is_main_contract_indi',
 'n_nearest_index_indi',
 'num_days',
 'num_durations',
 'indicator_cal_method',
 'freq',
 'freq_unit']

In [59]:
param_df = param_df.rename(columns = {"indicator_cal_method": "method"})

In [60]:
param_df = pd.merge(param_df, cal_indi_param_df, on  = ['index_col','is_main_contract_indi', 'n_nearest_index_indi','num_days','num_durations','method','freq', 'freq_unit'])

In [61]:
param_df.shape

(43, 27)

In [62]:
param_df = param_df.drop(columns = ['index_col','is_main_contract_indi', 'n_nearest_index_indi','num_days','num_durations','method','freq', 'freq_unit'])
param_df.columns

Index(['bottom', 'end_date', 'fut_pool_gen_method', 'fut_pool_gen_param',
       'future_pool', 'if_check_vol', 'if_save_res', 'ir',
       'is_main_contract_op', 'max_drawdown', 'n_nearest_index_op', 'res_dir',
       'returns', 'sharpe', 'start_date', 'std', 'top', 'weighted',
       'alpha_id'],
      dtype='object')

In [63]:
param_df[:3]

,bottom,end_date,fut_pool_gen_method,fut_pool_gen_param,future_pool,if_check_vol,if_save_res,ir,is_main_contract_op,max_drawdown,n_nearest_index_op,res_dir,returns,sharpe,start_date,std,top,weighted,alpha_id
0,0.10,2018-12-31,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,-0.007226,False,0.294970,1,eval_1211,0.004394,-0.114715,2010-01-01,847658.125707,0.10,False,hp-0
1,0.15,2018-12-31,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",True,True,0.008852,False,0.200350,1,eval_1211,0.037052,0.140515,2010-01-01,702043.753612,0.15,False,hp-0
2,0.10,2018-12-31,static,None,"[a, b, c, l, v, j, jm, m, p, y, fu, ru, al, au...",False,True,0.017185,True,0.181274,None,eval_1211,0.032458,0.272801,2010-01-01,827328.946729,0.10,False,hp-1

In [64]:
param_df["future_pool"] = param_df["future_pool"].map(lambda x: ",".join(x) if isinstance(x, list) else x )
param_df["fut_pool_gen_param"] = param_df["fut_pool_gen_param"].map(lambda x: str(x) if isinstance(x, dict) else x)

In [65]:
stra_elements = ["future_pool", "fut_pool_gen_method", "fut_pool_gen_param", "is_main_contract_op", "n_nearest_index_op",'if_check_vol', "weighted", "top", "bottom"]

In [66]:
stra_param_df = param_df[stra_elements]
 
print("before drop, there {} rows".format(stra_param_df.shape[0]))

stra_param_df = stra_param_df.drop_duplicates(subset = stra_param_df.columns, keep = "first")

print("after drop, there {} rows".format(stra_param_df.shape[0]))

before drop, there 43 rows
after drop, there 17 rows

In [67]:
stra_param_df["op_id"] = "op"

In [68]:
stra_param_df["id"] = np.arange(stra_param_df.shape[0])
stra_param_df["op_id"] = stra_param_df.apply(lambda x: x["op_id"] + "_" + str(x["id"]), axis = 1)
stra_param_df = stra_param_df.drop(columns = ["id"])

In [69]:
stra_param_df

,future_pool,fut_pool_gen_method,fut_pool_gen_param,is_main_contract_op,n_nearest_index_op,if_check_vol,weighted,top,bottom,op_id
0,"a,b,c,l,v,j,jm,m,p,y,fu,ru,al,au,cu,pb,rb,wr,z...",static,None,False,1,True,False,0.10,0.10,op_0
1,"a,b,c,l,v,j,jm,m,p,y,fu,ru,al,au,cu,pb,rb,wr,z...",static,None,False,1,True,False,0.15,0.15,op_1
2,"a,b,c,l,v,j,jm,m,p,y,fu,ru,al,au,cu,pb,rb,wr,z...",static,None,True,None,False,False,0.10,0.10,op_2
4,"a,b,c,l,v,j,jm,m,p,y,fu,ru,al,au,cu,pb,rb,wr,z...",static,None,False,1,False,False,0.15,0.15,op_3
5,"a,b,c,l,v,j,jm,m,p,y,fu,ru,al,au,cu,pb,rb,wr,z...",static,None,False,1,False,False,0.20,0.20,op_4
6,"a,b,c,l,v,j,jm,m,p,y,fu,ru,al,au,cu,pb,rb,wr,z...",static,None,False,1,False,False,0.10,0.10,op_5
16,"sr,c,cf,jd,cs,lr,wh,jr,pm,ap,cy,wt,er,cj,ri,ws...",static,None,False,3,NaN,NaN,NaN,NaN,op_6
17,"sr,c,cf,jd,cs,lr,wh,jr,pm,ap,cy,wt,er,cj,ri,ws...",static,None,False,3,NaN,NaN,NaN,NaN,op_7
20,"ss,al,cu,pb,wr,zn,ni,hc,au,ag,sn",static,None,True,None,NaN,NaN,NaN,NaN,op_8
21,"t,ts,ih,if,tf,ic",static,None,True,None,NaN,NaN,NaN,NaN,op_9
35,"a,b,c,l,v,j,jm,m,p,y,fu,ru,al,au,cu,pb,rb,wr,z...",static,None,True,None,False,False,0.15,0.15,op_10
37,None,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",False,3,NaN,NaN,NaN,NaN,op_11
38,None,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",False,3,NaN,NaN,NaN,NaN,op_12
39,None,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",False,3,NaN,NaN,NaN,NaN,op_13
40,None,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",False,3,NaN,NaN,NaN,NaN,op_14
41,None,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",False,3,NaN,NaN,NaN,NaN,op_15
42,None,dynamic,"{'type_list': ['能化', '金属'], 'cal_method': 'sin...",False,3,NaN,NaN,NaN,NaN,op_16

In [72]:
stra_param_df.to_csv("alpha_data" + os.sep + "op_param_df.csv", index = False)

In [70]:
param_df = pd.merge(param_df, stra_param_df, on = stra_elements)
param_df = param_df.drop(columns = stra_elements)

In [75]:
param_df = param_df.drop  (columns = ["res_dir", "if_save_res"])

In [76]:
param_df

,end_date,ir,max_drawdown,returns,sharpe,start_date,std,alpha_id,op_id
0,2018-12-31,-0.007226,0.294970,0.004394,-0.114715,2010-01-01,8.476581e+05,hp-0,op_0
1,2018-12-31,0.053105,0.231606,0.175981,0.843024,2010-01-01,1.281796e+06,in-1,op_0
2,2018-12-31,0.004788,0.263905,0.097428,0.076008,2010-01-01,1.331611e+06,in-3,op_0
3,2018-12-31,0.038655,0.140498,0.119091,0.613622,2010-01-01,9.041007e+05,oi-3,op_0
4,2018-12-31,0.008852,0.200350,0.037052,0.140515,2010-01-01,7.020438e+05,hp-0,op_1
5,2018-12-31,0.059496,0.176823,0.135429,0.944466,2010-01-01,1.052019e+06,in-1,op_1
6,2018-12-31,0.017185,0.181274,0.032458,0.272801,2010-01-01,8.273289e+05,hp-1,op_2
7,2018-12-31,-0.000738,0.289065,0.011090,-0.011718,2010-01-01,8.782764e+05,hp-2,op_2
8,2018-12-31,0.060348,0.212514,0.166163,0.957991,2010-01-01,1.314543e+06,in-1,op_2
9,2018-12-31,0.032485,0.256667,0.102729,0.515690,2010-01-01,1.250326e+06,in-2,op_2
10,2018-12-31,0.037937,0.126839,0.123657,0.602227,2010-01-01,9.060647e+05,oi-3,op_2
11,2018-12-31,0.035277,0.256491,0.098471,0.560003,2010-01-01,9.892406e+05,in-0,op_3
12,2018-12-31,0.069659,0.174384,0.131828,1.105802,2010-01-01,9.929405e+05,in-1,op_3
13,2018-12-31,0.028922,0.312836,0.070946,0.459126,2010-01-01,9.937017e+05,in-2,op_3
14,2018-12-31,0.053916,0.097382,0.128680,0.855894,2010-01-01,7.876990e+05,oi-0,op_3
15,2018-12-31,0.048351,0.099902,0.117564,0.767544,2010-01-01,7.614353e+05,oi-4,op_3
16,2018-12-31,0.053705,0.216983,0.135757,0.852534,2010-01-01,8.426286e+05,in-0,op_4
17,2018-12-31,0.052697,0.258388,0.144502,0.836535,2010-01-01,1.239022e+06,in-1,op_5
18,2018-12-31,0.029908,0.365413,0.116501,0.474774,2010-01-01,1.233906e+06,in-2,op_5
19,2018-12-31,0.014572,0.296795,0.139926,0.231321,2010-01-01,1.305272e+06,in-3,op_5
20,2018-12-31,0.055764,0.117536,0.158034,0.885227,2010-01-01,9.431770e+05,oi-0,op_5
21,2018-12-31,0.039365,0.176434,0.121745,0.624892,2010-01-01,9.107598e+05,oi-1,op_5
22,2018-12-31,0.054464,0.157314,0.166836,0.864583,2010-01-01,9.851781e+05,oi-2,op_5
23,2018-12-31,0.048917,0.141344,0.147724,0.776534,2010-01-01,9.631595e+05,oi-3,op_5
24,2018-12-31,-0.004680,0.313100,-0.014541,-0.074299,2010-01-01,9.109267e+05,mom-0,op_6
25,2018-12-31,-0.004680,0.313100,-0.014541,-0.074299,2010-01-01,9.109267e+05,mom-1,op_6
26,2018-12-31,-0.004680,0.313100,-0.014541,-0.074299,2010-01-01,9.109267e+05,mom-3,op_6
27,2018-12-31,0.005697,0.170853,0.011254,0.090441,2010-01-01,7.508733e+05,mom-0,op_7
28,2018-12-31,0.005697,0.170853,0.011254,0.090441,2010-01-01,7.508733e+05,mom-1,op_7
29,2018-12-31,0.005697,0.170853,0.011254,0.090441,2010-01-01,7.508733e+05,mom-3,op_7
30,2018-12-31,0.000460,0.253000,0.009753,0.007299,2010-01-01,9.329964e+05,mom-2,op_8
31,2018-12-31,0.000460,0.253000,0.009753,0.007299,2010-01-01,9.329964e+05,mom-4,op_8
32,2018-12-31,0.000460,0.253000,0.009753,0.007299,2010-01-01,9.329964e+05,mom-5,op_8
33,2018-12-31,0.022126,0.271557,0.097712,0.351235,2010-01-01,1.741489e+06,mom-2,op_9
34,2018-12-31,0.022126,0.271557,0.097712,0.351235,2010-01-01,1.741489e+06,mom-4,op_9
35,2018-12-31,0.022126,0.271557,0.097712,0.351235,2010-01-01,1.741489e+06,mom-5,op_9
36,2018-12-31,0.051917,0.095287,0.132840,0.824152,2010-01-01,7.191646e+05,oi-4,op_10
37,2018-12-31,0.084001,0.200072,0.254620,1.333470,2010-01-01,1.060385e+06,ts-0,op_11
38,2018-12-31,0.097498,0.179154,0.260501,1.547727,2010-01-01,9.044683e+05,ts-0,op_12
39,2018-12-31,0.100918,0.153475,0.261648,1.602030,2010-01-01,8.844195e+05,ts-0,op_13
40,2018-12-31,0.093832,0.177011,0.238170,1.489545,2010-01-01,8.510049e+05,ts-0,op_14
41,2018-12-31,0.093832,0.177011,0.238170,1.489545,2010-01-01,8.510049e+05,ts-0,op_15
42,2018-12-31,0.100918,0.153475,0.261648,1.602030,2010-01-01,8.844195e+05,ts-0,op_16

In [1]:
{i: list(param_df[i]) for i in param_df.columns}

NameError: name 'param_df' is not defined

In [78]:
param_df.to_csv("alpha_data" + os.sep + "performance.csv", index = False)